email = 'tadpoleslogin'
password = 'tadpolespassword'
localdir = '/somefolder/'
dbxtoken = 'dropboxtoken'
dbxfolder = '/dropboxfolder'
gmailuser = 'ilikeusing@gmail.com'
gmailpwd = 'gmailapppassword'
recipients = ['one@email.com', 'two@email.com', 'more@email.com']
dropfolder = 'https://www.dropbox.com/longlink'
droppreview = 'https://www.dropbox.com/home/foldername?preview='
kidsname = 'kidsname for subject line'